Contact form
victormc13/Portfolio-Microverse pull request #5
Opened 2023-01-25 19:22 UTC by victormc13

### Latest features in Portfolio-project
-----

- Add a "Contact form" section with all input fields to be filled in by the user.
- All input fields need to be completed to submit the form
- Add unordered lists for media-links
- Add a button to send the info on the form
- Add implementing button interactivity on button form: enabled, hover, active
- Add "a" tag for the contact email where you find me

2023-01-25 19:47 UTC, huseyinbiyik requested changes
Hi team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Form validations implemented well 👌
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- .gitignore used to ignore requested files 📁
- Commit messages are meaningful and written in imperative tense 📝
- PR description is descriptive 📝

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- to use Prettier plugin on VSCode, your code will be formatted and it will increase the readability of your code 👍

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 19:47 UTC, huseyinbiyik commented on index.html
> +				</button>
Brilliant job! 👌 But let's stick to the design and add a border to each side of the input areas. 
The green border around textarea implies the focus input attribute. When you click on the input areas it will turn to green. You can check the related topic here on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus).

<img width="467" alt="Screenshot 2023-01-25 at 10 32 00 PM" src="https://user-images.githubusercontent.com/25887253/214670428-9f8e6f8c-afd2-4f9f-847b-b0294a0cc409.png">
<img width="422" alt="Screenshot 2023-01-25 at 10 32 14 PM" src="https://user-images.githubusercontent.com/25887253/214670432-212bd7f4-3d3d-4a03-b3ff-b3c4e3339c8c.png">

2023-01-25 19:47 UTC, huseyinbiyik commented on index.html
> +				</button>
Your box-shadow looks great but the main goal of this project is coding the given design pixel-perfectly as you can see as a bullet point on the job ads. So let's fix our hover and pressed states according to the design provided.

<img width="540" alt="Screenshot 2023-01-25 at 10 33 37 PM" src="https://user-images.githubusercontent.com/25887253/214671165-3cad8184-400a-4516-8e2e-244d29dcf3c1.png">
<img width="392" alt="Screenshot 2023-01-25 at 10 34 06 PM" src="https://user-images.githubusercontent.com/25887253/214671168-936c5cc3-e696-487d-9d79-1630a5fe0415.png">

2023-01-25 23:56 UTC, Gambit142 requested changes
Hi @victormc13 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- All linters checks passed ✔️
- The correct HTML validations were used ✔️
- The form submits to Formspree ✔️

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 23:56 UTC, Gambit142 commented on style.css
- [ ] Great work removing the box shadow as the normal appearance. However, the previous reviewer asked that you make use of the Figma design for the `hover` state of the button. For the hover state, the button has a 
```CSS
box-shadow: 0px 8px 16px rgba(54, 179, 127, 0.24);
border-radius: 4px;
```

Kindly implement it according to the design. 👍

2023-01-26 00:55 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @victormc13, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-26 01:04 UTC, merged